# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-584cfacc-8903-4129-b845-ede590df54dc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-584cfacc-8903-4129-b845-ede590df54dc".device = "/dev/disk/by-uuid/584cfacc-8903-4129-b845-ede590df54dc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/62E0-E258";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/arch" =
    { device = "/dev/disk/by-uuid/49e09db5-a4ba-4790-b6e3-79fc890625dd";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-ed949a4c-1c52-4ac8-91cf-00a3d5c8b922"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
